### ISSUE TITLE
invalid page id or name 

### ISSUE THREAD

**Issue by bertenvdb** [jveldboom/facebook-gallery#23] opened 2016-05-26 02:28 UTC
I downloaded your code, uploaded it to my local webserver, did a chmod 777 but can't get past:

> invalid page id or name. 

Didn't touch your code, tried Taco Bell, X Games, Google Chrome and my personal page id... Can't figure out what's wrong. 

Any idea?

**Comment by jveldboom** [comment] 2016-05-27 12:08
What are you using as your page id or name?

**Comment by bertenvdb** [comment] 2016-05-28 12:49
I've tested these:
- tacobell
- XGames
- googlechrome
- Inkspiration1

**Comment by jveldboom** [comment] 2016-06-04 03:14
The issue is not with your Facebook page since it works here http://castletwo.com/facebook-gallery/?fid=Inkspiration1

See what it says by adding `var_dump($json_array)` on [line 183](https://github.com/jveldboom/facebook-gallery/blob/master/class.facebook-gallery.php#L183)

**Comment by zeusintuivo** [comment] 2016-08-27 21:20
I have the solution.

**Comment by jveldboom** [comment] 2016-08-28 02:30
@zeusintuivo are you going to provide some more information on how to fix the issue?

**Comment by zeusintuivo** [comment] 2016-08-28 13:17
Yup, I am working modifying the class now.

**Comment by fshabani** [comment] 2016-09-22 07:21
Is something here?

**Comment by zeusintuivo** [comment] 2016-09-24 10:36
I am still working with it.

**Comment by changeme** [comment] 2016-10-07 15:41
Any update?

Seems to be a deprecated function.

`array(1) { ["error"]=> array(4) { ["message"]=> string(52) "(#12) fql is deprecated for versions v2.1 and higher" ["type"]=> string(14) "OAuthException" ["code"]=> int(12) ["fbtrace_id"]=> string(11) "FXK2lsyrKyX" } } invalid page id or name`

**Comment by zeusintuivo** [comment] 2016-10-07 15:51
I am still ..not worked on it ,,, but I will look at it this weekend...

**Comment by pixelecho** [comment] 2016-10-14 10:40
any solutions now?

**Comment by zeusintuivo** [comment] 2016-10-20 09:15
I have been a little, but it is on back burner. I will look at it today

**Comment by fshabani** [comment] 2016-11-23 08:45
Any news?

**Comment by zeusintuivo** [comment] 2016-11-23 09:19
not yet, I will look at it this weekend again

**Comment by fshabani** [comment] 2016-12-19 14:40
Any news

**Comment by zeusintuivo** [comment] 2016-12-19 16:48
I just started to look at it,

**Comment by jveldboom** [comment] 2016-12-23 04:32
Sorry it took so long to jump into this. I think I've figured out what needs to happen to get this working again. Facebook made a change a while back that totally removed the FQL so the only way to do this is by using their SDK.

This is all fine but is going to require each person to register their app with Facebook to get a client id and client secret.

@zeusintuivo is this what you're seeing as well? If so, I'll continue refactoring the class to use the Facebook SDK v5.0.

**Comment by zeusintuivo** [comment] 2016-12-23 08:20
That is what I was working on. but now to use new sdk, you have to provide
certain level of steps to get the same result

**Comment by jveldboom** [comment] 2016-12-23 15:06
I just pushed up some rough working code to the "develop" branch. You'll
need to hard code you FB app I'd and secret key but it does work.

I'm planing on working on this next week once I get back from Christmas.
Will likely rewrite most of it and release it as 2.0.

Please feel free to pull down and start working on develop branch as well.
Pull requests always welcome and appreciated!

**Comment by zeusintuivo** [comment] 2016-12-23 15:26
yea my approach was also rewriting the whole thing, I will look into it.

**Comment by jveldboom** [comment] 2016-12-29 04:38
Just merged the fix into master. Released it as version 2.0 since quite a lot changes and really the old version will not work ever again. :( Check out the updated readme for instructions on how to get the update setup.

Closing this issue, but please feel free to open another one if you find any bugs or other issues. Thanks!

**Closed by jveldboom** 2016-12-29 04:38 UTC
